name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ramazanismayilov
          outputs: dist/snake.svg

      - name: Upload snake.svg artifact (optional, yoxlamaq üçün)
        uses: actions/upload-artifact@v4   
        with:
          name: snake-svg
          path: dist/snake.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
